USE master
GO

-- Drop the database if it already exists
IF  EXISTS (
	SELECT name 
		FROM sys.databases 
		WHERE name = N'QuanLyChungCu'
)
DROP DATABASE QuanLyChungCu
GO

CREATE DATABASE  QuanLyChungCu
GO

USE QuanLyChungCu

---------- Tables ----------

-- Account Table
CREATE TABLE TAIKHOAN
    (
      TenTaiKhoan VARCHAR(25) CONSTRAINT pk_TAIKHOAN PRIMARY KEY ,
      MatKhau VARCHAR(16) NOT NULL ,
      VaiTro BIT NOT NULL DEFAULT 0
    )
GO

-- Area Apartment Table
CREATE TABLE KHUCANHO(
	MaKhu CHAR(2) CONSTRAINT pk_KHUCANHO PRIMARY KEY,
	TenKhu NVARCHAR(50) NOT NULL,
	SoTang INT NOT NULL DEFAULT 1,
	SoCanTT INT NOT NULL DEFAULT 1,
	DiaChi NVARCHAR(100) NOT NULL,
	)

-- Resident Table
CREATE TABLE CUDAN(
	MaCuDan CHAR(6) CONSTRAINT pk_CUDAN PRIMARY KEY,
	TenCuDan NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL DEFAULT GETDATE(),
	GioiTinh BIT NOT NULL DEFAULT 0,
	SoDT CHAR(10) NOT NULL,
	SoCMT CHAR(12) NOT NULL,
	QueQuan NVARCHAR(100) NOT NULL
	)
GO

-- Apartment Table
CREATE TABLE CANHO(
	MaCanHo CHAR(6) CONSTRAINT pk_CANHO PRIMARY KEY,
	DienTich FLOAT NOT NULL DEFAULT 50,
	Gia BIGINT NOT NULL,
	TrangThai BIT NOT NULL DEFAULT 0,
	SoPhong INT NOT NULL DEFAULT 5,
	MaCuDan CHAR(6) NOT NULL DEFAULT '' CONSTRAINT fk1_CANHO FOREIGN KEY REFERENCES dbo.CUDAN(MaCuDan), 
	MaKhu CHAR(2) NOT NULL DEFAULT 'AA' CONSTRAINT fk2_CANHO FOREIGN KEY REFERENCES dbo.KHUCANHO(MaKhu) --  (AA -> ZZ)
)
GO

-- Contract Table
CREATE TABLE HOPDONG(
	MaHopDong CHAR(12) NOT NULL CONSTRAINT pk_HOPDONG PRIMARY KEY, -- HD0000000001
	NgayGiaoDich DATE NOT NULL DEFAULT GETDATE(),
	DiaChiKH NVARCHAR(100) NOT NULL,
	MaCuDan CHAR(6) NOT NULL CONSTRAINT fk1_HOPDONG FOREIGN KEY REFERENCES dbo.CUDAN(MaCuDan),
	MaCanHo CHAR(6) NOT NULL CONSTRAINT fk2_HOPDONG FOREIGN KEY REFERENCES dbo.CANHO(MaCanHo)
)

---------- Views ----------

---------- Storage Procedure ----------
